services:
    api:
      
      build:
        context: .
        dockerfile: ./Manguedu.Api/Dockerfile
      ports:
        - "8081:8080"
      depends_on:
        - database
    database:
      image: postgres
      environment:
        POSTGRES_DB: Manguedu
        POSTGRES_USER: develop
        POSTGRES_PASSWORD: develop
      ports:
        - "5432:5432"
      volumes:
        - db-data:/etc/data
    

volumes:
    db-data: